---
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name
name: "Upload archive to release"

# Define the trigger. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  release:
    types:
      - created

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:
  deploy:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
    uses: Good-Games-Munich/reusable-workflows/.github/workflows/production-archive-release.yml@main
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idwith
    with:
      build_command: npm run build
      to_zip_directory: dist
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
        contents: write